apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/danielvarsass/taskmanager-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: MongoDbSettings__ConnectionString
              value: "mongodb://mongodb:27017"
            - name: MongoDbSettings__DatabaseName
              value: "taskmanager"
            - name: MongoDbSettings__CollectionName
              value: "tasks"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
